apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-dev-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-dev/keycloak/pv/keycloak-pv"