apiVersion: v1
kind: Service
metadata:
  name: agrocrm-suite-with-mariadb-test-service
  namespace: agrotech-test
spec:
  selector:
    app: agrocrm-suite-with-mariadb-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#  type: NodePort
