apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrocrm-suite-with-mariadb-test-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-test/agrocrm-suite-with-mariadb/pv/agrocrm-with-mariadb-pv"
