apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agrocrm-suite-with-mariadb-test-pvc
  namespace: agrotech-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
