apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: chatbot
data:
  nginx-config.conf: |
    upstream django {
      server backend-service:5021;
    }

    upstream frontend {
      server frontend-service:5050;
    }

    upstream whatsapp {
      server whatsappbot:3301;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
      listen 5000;
      server_name chatbot.prodata.local;
      error_log /var/log/nginx/debug.log debug;


      location / {
        proxy_pass http://django;
      }

      location /ws/notifications {
          proxy_pass http://django;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
      }

      location /static/ {
        alias /static/;
      }
    }

    server {
      listen 3302;
      server_name infra.prodata.local;

      location / {
        proxy_pass http://whatsapp;
      }

    }

    server {
      listen 443;
      server_name chatbot.prodata.local;

      # location ^~ /api {
      #   proxy_pass http://django;
      #   #alias /;
      #   rewrite ^/api(/.*)$ $1 break;
      #   # proxy_pass http://backend-service:5021/$1;
      #   #rewrite ^/api(.*)$ $1 permanent;
      #   #return 301 /$1;
      #   #proxy_pass http://backend-service:5021;
      #   proxy_set_header Host $host;
      #   proxy_set_header X-Real-IP $remote_addr;
      #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #   proxy_set_header X-Forwarded-Proto $scheme;

      # }





      location / {
        proxy_buffer_size          256k;
        proxy_buffers              4 512k;
        proxy_busy_buffers_size    512k;
        proxy_pass http://frontend-service:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 60s;
        proxy_set_header Upgrade          $http_upgrade;
        proxy_set_header Connection       $http_connection;
        proxy_http_version 1.1;
      }

    #  location  /wsapi/ {
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    #     proxy_buffering off;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_pass http://backend-service:5021/$1;
    #   }



      #  location /api/ {
      #   proxy_pass http://backend-service:5021;
      # }



      location /_nuxt/hmr/ {
        proxy_pass http://frontend-service:24677;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    }