apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chatbot
  labels:
    app: redis-chatbot
spec:
  selector:
    app: redis-chatbot
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379