---
apiVersion: v1
kind: Service
metadata:
  name: agronewiki-db-prod-service
  namespace: agrotech-prod
spec:
  selector:
    app: agronewiki-db-prod
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432