apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agronewiki-db-prod-pvc
  namespace: agrotech-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 25Gi
