apiVersion: v1
kind: PersistentVolume
metadata:
  name: agronewiki-db-prod-pv
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/kubernetes/agrotech-prod/agronewiki/agronewikidb/pv/agronewiki-db-pv"
