
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pro-rti-prod-db-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-prod/pro-rti-prod-db/pv/pro-rti-prod-db-pv"  # Change this to the actual path on your host machine
