apiVersion: v1
kind: Service
metadata:
  name: psql-vidadi-service
  namespace: agrotech-dev
spec:
  type: NodePort
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30010  # You can choose any available port, this is just an example
