apiVersion: v1
kind: PersistentVolume
metadata:
  name: dwh-postgis-prod-db-pv
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-prod/agroflow/dwh-postgis-prod-db/pv/dwh-postgis-prod-db-pv"  # Change this to the actual path on your host machine
