apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwh-postgis-prod-db-pvc
  namespace: agrotech-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
