version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /home/prdadm/postgress/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=prodata
      - POSTGRES_USER=prodata
      - POSTGRES_DB=prodata