apiVersion: v1
kind: PersistentVolume
metadata:
  name: agroflow-db-pv
  namespace: agrotech-dev
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/kubernetes/agrotech-dev/agroflow/agroflow-db/pv/agroflow-db-pv"
