apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agrocrm-suite-mariadb-prod-pvc
  namespace: agrotech-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
