apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agrocrm-suite-mariadb-pvc
  namespace: agrotech-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
