---
apiVersion: v1
kind: Service
metadata:
  name: agrocrm-service
  namespace: agrotech-dev
spec:
  type: NodePort
  selector:
    app: agrocrm
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001  # Assign a specific NodePort number, e.g., 31000