apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrocrm-db-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/prdadm/agrocrm/pv/agrocrm-pv"
