apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrogeo-dev-data-eng-pv
spec:
  capacity:
    storage: 5Gi # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-dev/agrogeoserver/agrogeo-dev-data-eng/pvagrogeo-dev-data-eng/pv/agrogeo-dev-data-eng-pv" # Replace with the actual path on your host machine
