apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrocrm
  namespace: agrotech-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrocrm
  template:
    metadata:
      labels:
        app: agrocrm
    spec:
      containers:
      - name: agrocrm
        image: bitnami/suitecrm
        env:
          - name: DB_TYPE
            value: "postgresql"
          - name: DB_HOST
            value: "agrocrm-db"  # Replace with your PostgreSQL host
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "agrocrm"  # Replace with your PostgreSQL database name
          - name: DB_USER
            value: "agrocrm"  # Replace with your PostgreSQL username
          - name: DB_PASSWORD
            value: "agrocrm"  # Replace with your PostgreSQL password
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: SUITECRM_DATABASE_USER
            value: "agrocrm"
          - name: SUITECRM_DATABASE_PASSWORD
            value: "agrocrm"
          - name: SUITECRM_DATABASE_NAME
            value: agrocrm
        ports:
        - containerPort: 8080
#        volumeMounts:
#        - name: agrocrm-pvc
#          mountPath: /bitnami/suitecrm
#      volumes:
#      - name: agrocrm-pvc
#        persistentVolumeClaim:
#          claimName: agrocrm-pvc

