apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatbot-postgresql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prdadm/chatbot/pv/postgresql"