apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrogeo-test-pv
spec:
  capacity:
    storage: 5Gi # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-test/agrogeoserver/pv/agrogeo-test-pv" # Replace with the actual path on your host machine
