apiVersion: v1
kind: Service
metadata:
  name: agrogeoserver-dev-data-eng-nginx-proxy-deployment-nginx-service
  namespace: agrotech-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: agrogeoserver-dev-data-eng-nginx-proxy
#status:
#  loadBalancer: {}