apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agrogeo-dev-data-eng-pvc
  namespace: agrotech-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Must match the storage size in the corresponding PV
