apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-postgresql-claim
  namespace: chatbot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi