apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-frontend-pvc-1
  namespace: chatbot
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi