apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrogis-server-pv
  namespace: agrotech-dev
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/kubernetes/agrotech-dev/agrogis-server/pv/agrogis-server-pv"
