apiVersion: v1
kind: Service
metadata:
  name: telegrambot
  namespace: chatbot
spec:
  selector:
    app: telegrambot
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      name: tgbot-1