apiVersion: v1
kind: PersistentVolume
metadata:
  name: agroflow-db-dev-pv
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/kubernetes/agrotech-dev/agroflow/pv/agroflow-redis-dev-pv"
