apiVersion: v1
kind: Service
metadata:
  name: bookstack-dev-service
  namespace: agrotech-dev
spec:
  selector:
    app: bookstack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#  type: NodePort