apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-pv
spec:
  capacity:
    storage: 10Gi # Set any value you prefer
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "YOUR Directory" # Replace with your real directory on your host