
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pro-rti-db-dev-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-dev/agroflow/pro-rti-dev-db/pv/pro-rti-db-dev-pv"  # Change this to the actual path on your host machine
