apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrocrm-suite-mariadb-dev-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-dev/agrocrm/agrocrm-maria/maria/pv/agrocrm-maria-pv"