apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agrocrm-suite-with-mariadb-dev-pvc
  namespace: agrotech-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
