apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrogeoserver-test
  namespace: agrotech-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrogeoserver-test
  template:
    metadata:
      labels:
        app: agrogeoserver-test
    spec:
      containers:
      - name: agrogeoserver-test
        image: docker.osgeo.org/geoserver:2.24.2
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: INSTALL_EXTENSIONS
            value: "true"
          - name: STABLE_EXTENSIONS
            value: "authkey"
          - name: SKIP_DEMO_DATA
            value: "true"
          - name: ROOT_WEBAPP_REDIRECT
            value: "true"
#          - name: SSL
#            value: "true"
#          - name: GEOSERVER_HTTPS_PORT
#            value: "8443"
#          - name: GEOSERVER_HTTPS_KEYSTORE_LOCATION
#            value: /var/geoserver/data/security/keystore
#          - name: GEOSERVER_HTTPS_KEYSTORE_PASSWORD
#            value: "changeit"
#          - name: GEOSERVER_HTTPS_KEYSTORE_TYPE
#            value: PKCS12
#          - name: GEOSERVER_HTTPS_KEYSTORE_ALIAS
#            value: "geoserver"
#
#        volumeMounts:
#          - name: keystore-volume
#            mountPath: /var/geoserver/data/security/keystore
#        volumes:
#          - name: keystore-volume
#            secret:
#              secretName: geoserver-tls-secret

---
