apiVersion: v1
kind: PersistentVolume
metadata:
  name: fms-db-dev-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-dev/agroflow/fms-dev-db/pv/fms-db-dev-pv"  # Change this to the actual path on your host machine
