apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-prod-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-prod/keycloak/pv/keycloak-prod-pv"