apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-backend-pvc
  namespace: chatbot
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi