apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fms-postgis-prod-db-pvc
  namespace: agrotech-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
