apiVersion: v1
kind: PersistentVolume
metadata:
  name: fms-postgis-prod-db-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-prod/fms-postgis-prod-db/pv/fms-postgis-prod-db-pv"  # Change this to the actual path on your host machine
