apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwh-postgis-test-db-pvc
  namespace: agrotech-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
