apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agronewiki-dev-pvc
  namespace: agrotech-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 25Gi
