apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agrocrmdb
  namespace: agrotech-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrocrmdb
  template:
    metadata:
      labels:
        app: agrocrmdb
    spec:
      initContainers:
        - name: mariadb-create-directory-structure
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /bitnami/mariadb/data && chown -R 1001:1001 /bitnami",
            ]
          volumeMounts:
            - name: agrocrmdb-persistent-storage
              mountPath: /bitnami
      containers:
        - name: agrocrmdb
          image: bitnami/mariadb
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MARIADB_DATABASE
              value: "suitecrm"
            - name: MARIADB_USER
              value: "suitecrm"
            - name: MARIADB_PASSWORD
              value: "suitecrm"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /bitnami/mariadb
              name: agrocrmdb-persistent-storage
      volumes:
        - name: agrocrmdb-persistent-storage
          persistentVolumeClaim:
            claimName: agrocrmdb-pvc
