apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrocrmdb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrocrm/agrocrmdb/pv/agrocrmdb-pv"
