apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fms-postgis-test-db-pvc
  namespace: agrotech-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
