apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-test-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-test/keycloak/keycloak-db/pv/keycloak-db-pv"