apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-test
  namespace: agrotech-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-test
  template:
    metadata:
      labels:
        app: keycloak-test
    spec:
      containers:
        - name: keycloak-test
          image: quay.io/keycloak/keycloak
          args: ["start-dev"]
          imagePullPolicy: Always
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: keycloak-test-db-service
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: keycloak
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - name: keycloak-test-storage
              mountPath: /opt/jboss/keycloak-test/standalone/data
      volumes:
        - name: keycloak-test-storage
          persistentVolumeClaim:
            claimName: keycloak-test-pvc



