apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-test-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubernetes/agrotech-test/keycloak/pv/keycloak-test-pv"