apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: chatbot
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 5021
      targetPort: 5021
      name: back-1

    - name: back-2
      protocol: TCP
      targetPort: 2525
      port: 2525