apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatbot-backend-pv
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prdadm/chatbot/pv/chatbot_backend"