apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: agrone-ceph-fs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: agrone-ceph-fs
      replicated:
        size: 2
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true