apiVersion: v1
kind: PersistentVolume
metadata:
  name: agronewiki-db-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/prdadm/agronewiki/pv/agronewiki-db-pv"
