apiVersion: v1
kind: PersistentVolume
metadata:
  name: agrodb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/prdadm/agronewiki/pv/agrodb-pv"
