apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agrodb-pvc
  namespace: agrotech-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
