apiVersion: v1
kind: PersistentVolume
metadata:
  name: agronewiki-test-pv
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/kubernetes/agrotech-test/agronewiki/pv/agronewiki-pv"
