---
apiVersion: v1
kind: Service
metadata:
  name: agronewiki-db-test-service
  namespace: agrotech-test
spec:
  selector:
    app: agronewiki-db-test
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432