---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: agrotech-dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/home/prdadm/agrocrm/pv/agrocrm-db-pv"
