apiVersion: v1
kind: Service
metadata:
  name: suitecrm-service
  namespace: agrotech-dev
spec:
  selector:
    app: suitecrm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort