apiVersion: v1
kind: PersistentVolume
metadata:
  name: suitecrm-pv
  namespace: agrotech-dev
spec:
  capacity:
    storage: 5Gi  # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prdadm/agrocrm/pv/agrocrm-pv"  # Adjust the host path as needed